[build]
  command = "npm i && npm run build"
  publish = "dist/remote-v12-app"
  [build.environment]
    NODE_VERSION = "16.20.2"
    NPM_FLAGS = "--no-audit --no-fund"

[[headers]]
for = "/remoteEntry.js"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
for = "/*.js"
[headers.values]
Access-Control-Allow-Origin = "*"
